[package]
name = "nanoc-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
nanoc-parser.workspace = true
nanoc-analyzer.workspace = true

inkwell.workspace = true
rowan.workspace = true
insta.workspace = true
