[package]
name = "parser"
version.workspace = true
edition.workspace = true

[dependencies]
syntax.workspace = true
lexer.workspace = true

text-size.workspace = true
rowan.workspace = true
insta.workspace = true
thiserror.workspace = true
