[package]
name = "airyc-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
airyc-parser.workspace = true
airyc-analyzer.workspace = true

inkwell.workspace = true
rowan.workspace = true
insta.workspace = true
