[package]
name = "nanoc-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
logos.workspace = true
text-size.workspace = true
thiserror.workspace = true
rowan.workspace = true
insta.workspace = true
