[package]
name = "lexer"
version.workspace = true
edition.workspace = true

[dependencies]
syntax.workspace = true
tools.workspace = true

logos.workspace = true
thiserror.workspace = true
miette.workspace = true
