name: Rust

on:
  push:
    branches: [ "main", "ci"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust-Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/widsnoy/rust-llvm19:latest
    steps:
      - uses: actions/checkout@v4
      - name: fmt & clippy & test
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace --all-targets --all-features -- -D warnings
          cargo build --verbose --workspace
          cargo test --verbose --workspace
