name: Rust

on:
  push:
    branches: [ "main", "ci"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust-Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/widsnoy/rust-llvm21:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Cargo build
        run: cargo build --verbose --workspace
      - name: Cargo test
        run: cargo test --verbose --workspace
      - name: Run tests
        run: cd test && bash ./test.sh 1 3 4 5 6 7 8 9
